window.caseAssets = {
  "CASE-WHERE-RESULT-01": {
    svg: "lp-patterns-focus.svg",
    alt: "Фокус на паттерне вопроса про результат",
    lp: "LP-PATTERNS-01",
    lpLabel: "patterns",
  },
  "CASE-DIGNITY-RATING-01": {
    svg: "lp-self-pyramid.svg",
    alt: "Пирамида собственной ценности и достоинства",
    lp: "LP-SELF-01",
    lpLabel: "self",
  },
  "CASE-SYSTEM-INSTEAD-SELF-01": {
    svg: "second-brain.svg",
    alt: "Второй мозг и перегруз инфраструктурой",
    lp: "LP-RELEARN-01",
    lpLabel: "relearn",
  },
  "CASE-PLAN-IDOL-01": {
    svg: "intent-economy.svg",
    alt: "Экономика намерения и подмена цели планом",
    lp: "LP-PATTERNS-01",
    lpLabel: "patterns",
  },
  "CASE-REALIZATION-FLAG-01": {
    svg: "lp-relearn-pipeline.svg",
    alt: "Переобучение реализации шаг за шагом",
    lp: "LP-RELEARN-01",
    lpLabel: "relearn",
  },
  "CASE-RIGHT-PLAN-01": {
    svg: "lp-marn-filter.svg",
    alt: "Фильтр живого импульса перед построением плана",
    lp: "LP-SELF-01",
    lpLabel: "self",
  },
  "CASE-FEEDBACK-TRUTH-01": {
    svg: "context-ai.svg",
    alt: "Внешний контекст и чтение собственной ценности",
    lp: "LP-SELF-01",
    lpLabel: "self",
  },
  "CASE-PERMISSION-REST-01": {
    svg: "exoskeleton.svg",
    alt: "Право на отдых без внешнего экзоскелета одобрения",
    lp: "LP-SELF-01",
    lpLabel: "self",
  },
  "CASE-GIVE-RESULT-01": {
    svg: "cm-mkuypomn-uhzhbr.svg",
    alt: "Передача результата и динамика двух сторон",
    lp: "LP-RELEARN-01",
    lpLabel: "relearn",
  },
  "CASE-CAN-MUST-01": {
    svg: "lp-science-network.svg",
    alt: "Сеть обязанностей и центр собственной ответственности",
    lp: "LP-SELF-01",
    lpLabel: "self",
  },
  "CASE-TIME-BELONGS-01": {
    svg: "four-weeks.svg",
    alt: "Ритм и возврат хозяина своему времени",
    lp: "LP-RELEARN-01",
    lpLabel: "relearn",
  },
  "CASE-NEGATIVITY-DRAIN-01": {
    svg: "digital-twin.svg",
    alt: "Свое состояние рядом с чужим эмоциональным полем",
    lp: "LP-PATTERNS-01",
    lpLabel: "patterns",
  },
  "CASE-CLUB-IMPULSE-01": {
    svg: "lp-science-network.svg",
    alt: "Живая идея клуба и сеть возможных связей",
    lp: "LP-SELF-01",
    lpLabel: "self",
  },
  "CASE-PRICE-SHAME-01": {
    svg: "lp-self-pyramid.svg",
    alt: "Право занимать место и спокойно называть цену",
    lp: "LP-SELF-01",
    lpLabel: "self",
  },
  "CASE-IMPULSE-LATER-01": {
    svg: "second-brain.svg",
    alt: "Живой импульс, который нельзя оставлять только во втором мозге",
    lp: "LP-SELF-01",
    lpLabel: "self",
  },
  "CASE-SUCCESS-SHAME-01": {
    svg: "exoskeleton.svg",
    alt: "Внешний уровень жизни и внутреннее право на него",
    lp: "LP-SELF-01",
    lpLabel: "self",
  },
  "CASE-CREDIT-LOOP-01": {
    svg: "intent-economy.svg",
    alt: "Денежная петля, где нехватка автоматически превращается в заем",
    lp: "LP-PATTERNS-01",
    lpLabel: "patterns",
  },
  "CASE-RESTART-ZERO-01": {
    svg: "four-weeks.svg",
    alt: "Ритм, который возвращается после паузы без обнуления",
    lp: "LP-RELEARN-01",
    lpLabel: "relearn",
  },
  "CASE-BUYIN-NOD-01": {
    svg: "context-ai.svg",
    alt: "Контекст и артефакты против пустого внешнего согласия",
    lp: "LP-RELEARN-01",
    lpLabel: "relearn",
  },
  "CASE-MICROMANAGE-FEAR-01": {
    svg: "cm-mkuypomn-uhzhbr.svg",
    alt: "Две стороны игры и рамка вместо ручного контроля",
    lp: "LP-PATTERNS-01",
    lpLabel: "patterns",
  },
  "CASE-SCROLL-RELIEF-01": {
    svg: "digital-twin.svg",
    alt: "Цифровой двойник как поздний сброс накопленного перегруза",
    lp: "LP-PATTERNS-01",
    lpLabel: "patterns",
  },
};

window.caseLpFilters = [
  {
    key: "LP-PATTERNS-01",
    label: "patterns",
    title: "LP-PATTERNS-01",
    svg: "lp-patterns-focus.svg",
    alt: "Фильтр кейсов по Learning Path Patterns",
  },
  {
    key: "LP-SELF-01",
    label: "self",
    title: "LP-SELF-01",
    svg: "lp-self-pyramid.svg",
    alt: "Фильтр кейсов по Learning Path Self",
  },
  {
    key: "LP-RELEARN-01",
    label: "relearn",
    title: "LP-RELEARN-01",
    svg: "lp-relearn-pipeline.svg",
    alt: "Фильтр кейсов по Learning Path Relearn",
  },
  {
    key: "all",
    label: "all paths",
    title: "Все кейсы",
    svg: "four-weeks.svg",
    alt: "Сброс LP-фильтра и показ всех кейсов",
  },
];
