plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/meganom26/sync/IMT sync/МГ2/30_metaIMT/Контент/LP/CASE-WHERE-RESULT-01"
publishOrigin = "config"
base = "/Users/meganom26/sync/IMT sync/МГ2/30_metaIMT/Контент/LP/CASE-WHERE-RESULT-01"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]