export const categories = [
  {
    id: "self-development",
    label: "Self-development",
    description: "Системы для обучения, самонаблюдения и работы с личным контекстом.",
    accent: "green",
  },
  {
    id: "content",
    label: "Создание контента",
    description: "Конвейеры, которые превращают разговоры и идеи в опубликованные материалы.",
    accent: "blue",
  },
  {
    id: "consulting",
    label: "Для консультанта ИМТ",
    description: "Инструменты анализа консультационных материалов с обязательной проверкой человеком.",
    accent: "red",
  },
  {
    id: "equipment",
    label: "Данные и оборудование",
    description: "Локальные наблюдения и измерения, встроенные в личную практику.",
    accent: "violet",
  },
  {
    id: "automation",
    label: "Практичные автоматизации",
    description: "Небольшие системы для конкретных бытовых задач.",
    accent: "ochre",
  },
];

export const statusLabels = {
  used: "используется",
  ready: "готов показывать",
  prototype: "прототип",
  experiment: "эксперимент",
};

export const artifacts = [
  {
    id: "lecture-processing-skill",
    slug: "lecture-processing-skill",
    title: "Скилл обработки лекций ИМТ",
    category: "self-development",
    status: "used",
    outcome: "Собирает полный пакет лекции, семинара, методички и домашней работы в связный учебный контекст.",
    proof: "есть валидаторы и тесты",
    readyToShow: false,
    image: null,
    imageAlt: "Плейсхолдер для скилла обработки лекций ИМТ",
    detailUrl: null,
    format: "Codex skill",
  },
  {
    id: "personal-daily-system",
    slug: "personal-daily-system",
    title: "Личная система трекинга ЖС в Codex",
    category: "self-development",
    status: "used",
    outcome: "Связывает ежедневные решения с лестницей целей и сохраняет наблюдения о жизнеспособности.",
    proof: "использую ежедневно",
    readyToShow: false,
    image: null,
    imageAlt: "Плейсхолдер для личной системы трекинга ЖС",
    detailUrl: null,
    format: "Codex workflow",
  },
  {
    id: "telegram-openclaw-dashboard",
    slug: "telegram-openclaw-dashboard",
    title: "Telegram/OpenClaw-бот с дашбордом",
    category: "self-development",
    status: "used",
    outcome: "Переносит утренний и вечерний ритм в Telegram и показывает актуальное состояние системы.",
    proof: "работает в личном контуре",
    readyToShow: false,
    image: null,
    imageAlt: "Плейсхолдер для Telegram и OpenClaw-бота",
    detailUrl: null,
    format: "Telegram bot + web",
  },
  {
    id: "session-context-posters",
    slug: "session-context-posters",
    title: "Саммари сессии, личный контекст и плакаты",
    category: "self-development",
    status: "used",
    outcome: "Превращает разговор и накопленный контекст в короткое продолжение работы между сессиями.",
    proof: "есть готовые prompt-пакеты",
    readyToShow: false,
    image: null,
    imageAlt: "Плейсхолдер для сессионных саммари и плакатов",
    detailUrl: null,
    format: "workflow + документы",
  },
  {
    id: "bsz",
    slug: "bsz",
    title: "БСЗ",
    category: "self-development",
    status: "ready",
    outcome: "Сохраняет совершенные знания как проверяемую структуру с источниками и связями.",
    proof: "есть безопасный пример",
    readyToShow: true,
    image: null,
    imageAlt: "Плейсхолдер для базы совершенных знаний",
    detailUrl: null,
    format: "база знаний",
  },
  {
    id: "bsk",
    slug: "bsk",
    title: "БСК",
    category: "self-development",
    status: "ready",
    outcome: "Собирает смысловые коды из материалов и делает их доступными для повторного использования.",
    proof: "есть индекс и workflow",
    readyToShow: true,
    image: null,
    imageAlt: "Плейсхолдер для базы смысловых кодов",
    detailUrl: null,
    format: "карточки + индекс",
  },
  {
    id: "imt-2033",
    slug: "imt-2033",
    title: "Сайт 2033",
    category: "content",
    status: "used",
    outcome: "Показывает высший срез ИМТ через самостоятельный опубликованный web-проект.",
    proof: "опубликовано",
    readyToShow: false,
    image: null,
    imageAlt: "Плейсхолдер для сайта 2033",
    detailUrl: null,
    format: "web",
  },
  {
    id: "call-to-article-drafts",
    slug: "call-to-article-drafts",
    title: "Драфты статей по созвонам",
    category: "content",
    status: "prototype",
    outcome: "Выделяет из транскриптов созвонов темы и собирает первые версии будущих статей.",
    proof: "есть рабочий pipeline",
    readyToShow: false,
    image: null,
    imageAlt: "Плейсхолдер для драфтов статей по созвонам",
    detailUrl: null,
    format: "Content Ledger",
  },
  {
    id: "illustrated-articles",
    slug: "illustrated-articles",
    title: "Создание статей с изображениями",
    category: "content",
    status: "used",
    outcome: "Собирает текст, иллюстрации и web-вёрстку статьи в единый воспроизводимый процесс.",
    proof: "есть опубликованные статьи",
    readyToShow: false,
    image: null,
    imageAlt: "Плейсхолдер для создания статей с изображениями",
    detailUrl: null,
    format: "article builder",
  },
  {
    id: "article-to-video",
    slug: "article-to-video",
    title: "Создание роликов по статье",
    category: "content",
    status: "used",
    outcome: "Переводит готовую статью в сценарий, сцены и собранный видеоролик.",
    proof: "есть production baseline",
    readyToShow: false,
    image: null,
    imageAlt: "Плейсхолдер для конвейера создания роликов",
    detailUrl: null,
    format: "video pipeline",
  },
  {
    id: "jfv-from-transcript",
    slug: "jfv-from-transcript",
    title: "Построение ЖФВ по транскрипту",
    category: "consulting",
    status: "prototype",
    outcome: "Помогает собрать черновую структуру ЖФВ из консультационного транскрипта для проверки консультантом.",
    proof: "есть развиваемая схема",
    readyToShow: false,
    image: null,
    imageAlt: "Плейсхолдер для построения ЖФВ по транскрипту",
    detailUrl: null,
    format: "analysis workflow",
  },
  {
    id: "genogram-from-transcript",
    slug: "genogram-from-transcript",
    title: "Генограмма по транскрипту",
    category: "consulting",
    status: "prototype",
    outcome: "Извлекает подтверждённые родственные связи и готовит генограмму к human review.",
    proof: "есть skill, provenance и тесты",
    readyToShow: false,
    image: null,
    imageAlt: "Плейсхолдер для генограммы по транскрипту",
    detailUrl: null,
    format: "skill + FigJam/export",
  },
  {
    id: "anonymized-transcript-cases",
    slug: "anonymized-transcript-cases",
    title: "Обезличенные кейсы по транскриптам",
    category: "consulting",
    status: "ready",
    outcome: "Показывает ход и результат работы без раскрытия личности и исходного транскрипта.",
    proof: "есть публичные case pages",
    readyToShow: true,
    image: null,
    imageAlt: "Плейсхолдер для обезличенных кейсов",
    detailUrl: null,
    format: "web cases",
  },
  {
    id: "muse-mountain-practice",
    slug: "muse-mountain-practice",
    title: "Muse: практика «подъём на гору»",
    category: "equipment",
    status: "experiment",
    outcome: "Проверяет, как нейрообратная связь сочетается с личной дыхательной практикой.",
    proof: "есть личные измерения",
    readyToShow: false,
    image: null,
    imageAlt: "Плейсхолдер для практики с Muse Headband",
    detailUrl: null,
    format: "Muse Headband + практика",
  },
  {
    id: "focus-observer",
    slug: "focus-observer",
    title: "Focus Observer",
    category: "equipment",
    status: "used",
    outcome: "Локально замечает выход из фокус-сессии и помогает вернуться к выбранной задаче.",
    proof: "использую сам",
    readyToShow: false,
    image: null,
    imageAlt: "Плейсхолдер для Focus Observer",
    detailUrl: "/artifacts/focus-observer/",
    format: "macOS app + skill",
  },
  {
    id: "genome-review",
    slug: "genome-review",
    title: "Проверка генома",
    category: "equipment",
    status: "ready",
    outcome: "Собирает несколько интерпретаций WGS-данных в проверяемый сравнительный разбор.",
    proof: "есть обезличенный сценарий показа",
    readyToShow: true,
    image: null,
    imageAlt: "Плейсхолдер для проверки генома",
    detailUrl: null,
    format: "WGS reports",
  },
  {
    id: "shopping-monitor",
    slug: "shopping-monitor",
    title: "Shopping Monitor",
    category: "automation",
    status: "prototype",
    outcome: "Проверяет наличие нужного размера и скидки, не заставляя вручную обходить магазины.",
    proof: "есть plugin, адаптеры и тесты",
    readyToShow: false,
    image: null,
    imageAlt: "Плейсхолдер для Shopping Monitor",
    detailUrl: null,
    format: "OpenClaw plugin",
  },
];
